import Head from "next/head";
import Image from "next/image";
import SpotifyButton from "~/components/SignInButtonSpotify";
import { useSession } from "next-auth/react";
// import { api } from "~/utils/api";

export default function Home() {
  const { data: session } = useSession();
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Quizlics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/quizlics_logo_transparent_blue.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#198AFD] to-[#1A193F]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image
            src={"/quizlics_transparent_white.png"}
            width={200}
            height={200}
            alt="quilics logo"
          />
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Let's play <span className="text-[#076AE0]">Quizlics</span>
          </h1>
          {session ? <>welcome {session.user?.name}</> : <SpotifyButton />}
        </div>
      </main>
    </>
  );
}
